<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Title>RepoDb.Oracle</Title>
    <TargetFrameworks>net10.0;net9.0;netstandard2.1</TargetFrameworks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Description>A hybrid .NET ORM library for Oracle.</Description>
    <PackageTags>orm hybrid-orm micro-orm Oracle npgsql</PackageTags>
    <PackageReleaseNotes>https://repodb.net/release/Oracle</PackageReleaseNotes>
    <PackageProjectUrl>https://github.com/AmpScm/RepoDB/tree/master/src/RepoDb.Oracle/</PackageProjectUrl>
    <PackageId>$(PackagePrefix)$(AssemblyName)</PackageId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Oracle.ManagedDataAccess.Core"/>
    <ProjectReference Include="..\RepoDb\RepoDb.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\RepoDb\Compat.cs" />
    <None Include="README.md" Pack="True" PackagePath="\" />
  </ItemGroup>
</Project>
